### ISSUE TITLE
Add container classes

### ISSUE THREAD

**Issue by caufieldjh** [bridge2ai/standards-schemas#8]
Container classes allow sets of data objects to be defined together, like in [this example borrowed from the LinkML tests](https://github.com/linkml/linkml/blob/main/tests/test_validation/input/kitchen_sink_inst_01.yaml):
```
persons:
  - id: P:001
    name: fred bloggs
    age_in_years: 33
  - id: P:002
    name: joe schmoe
    has_employment_history:
      - employed_at: ROR:1
        started_at_time: 2019-01-01
        is_current: true
```

In that example, the schema defines the container like this:
```
classes:
  Dataset:
    attributes:
      persons:
        range: Person
        inlined: true
        inlined_as_list: true
        multivalued: true
```

It could also look like:
```
classes:
  Container:
    tree_root: true
    slots:
      - name
      - persons
      - organizations
      - places

slots:
  persons:
    range: Person
    inlined: true
    inlined_as_list: true
    multivalued: true
```

The containers could be defined in a generic way for `standards-schemas` within `standards_schema_all.yaml`, but that limits some of the point of having the schemas treated as different modules. The modules could still have their own container types, defined in each schema.
